### ISSUE TITLE
chars parameter cutting off randomly

### ISSUE THREAD

**Issue by octopusxl** [BlackBeltDesigns/bbd_chopper.ee_addon#1]
Thanks for porting over Hacksaw! I was sad when they stopped developing it. I have an issue with the chars parameter though:

`{exp:chopper chars="1"}{logged_in_screen_name}{/exp:chopper}`

This returns 2 characters. "0" will return 1 character, "4" returns 2 and so on. Am I misunderstanding the chars usage?

**Comment by BlackBeltDesigns** [comment]
I am so sorry to just be seeing this. I didn't receive a notice and hadn't been back here in a while.   :(

I looked at the issue and saw where I was adding a character incorrectly. I am sorry again.  I am uploading a new version right now. Please let me know if this fixes your issues. Feel free to email me directly brian.mallett at bbdokc dot com for any issues you see weith this version.

**Comment by octopusxl** [comment]
Thanks for looking into it, it works perfect now!
