### ISSUE TITLE
Using "Chars" in 3.4.7 Generates Sting Of Numbers In Body

### ISSUE THREAD

**Issue by FirstClassCode** [BlackBeltDesigns/bbd_chopper.ee_addon#3]
Hi there,

First off thank you very much for this plugin. It has been helpful. However, I have been stuck using "words" to limit my text because using "chars" generates a string of numbers and appends it to the top of the body on any page it is being used on.

Perhaps I have configured something incorrectly? If so, please do let me know.

Thanks
-Reece

**Comment by BlackBeltDesigns** [comment]
I changed the way the characters parameter was being stripped and truncated. I just uploaded a new version to devot:ee and am uploading this one now. 

Let me know how that works out for you. 

Also, If you like it, and wouldn't mind leaving a rating on devot:ee, it actually helps.  :)

Thanks,
Brian
